export type Locale = "zh" | "en";

export const copy = {
  zh: {
    intro: {
      title: "专业的游戏服务器管理，从容而简单",
      body: "在清晰统一的界面中管理游戏、模组、存档与联机信息。",
      kicker: "轻量 · 清晰 · 可靠",
    },
    library: {
      eyebrow: "多游戏支持",
      title: "多款游戏，统一管理",
      body: "在一个面板中完成泰拉瑞亚、饥荒联机版、幻兽帕鲁和我的世界服务器的创建、配置与启停。",
      create: "创建服务器",
      ready: "配置完成",
    },
    mods: {
      eyebrow: "模组管理",
      title: "模组管理，清晰高效",
      body: "集中完成模组检索、安装与启用，名称、大小及运行要求清晰呈现。",
      heading: "安装模组",
      hint: "从平台模组库中选择，相关变更将在服务器重启后生效。",
      library: "模组库 20",
      packs: "模组包 1",
      installed: "已安装",
      install: "安装",
      serverOnly: "仅服务端",
      both: "服务端与客户端",
    },
    backups: {
      eyebrow: "存档与备份",
      title: "可靠备份，守护每一次游戏进度",
      body: "支持即时保存、自动备份与快速恢复，为游戏世界提供持续可靠的保护。",
      save: "立即保存世界",
      backup: "创建备份",
      restore: "恢复此版本",
      now: "刚刚",
      yesterday: "昨天 23:30",
      beforeUpdate: "更新模组前",
      auto: "自动备份",
      manual: "手动备份",
    },
    invite: {
      eyebrow: "好友联机",
      title: "快速分享，便捷联机",
      body: "服务器地址、端口和密码自动整理为邀请信息，便于安全准确地分享给好友。",
      heading: "游戏服务器邀请",
      online: "服务器在线",
      address: "连接地址",
      password: "房间密码",
      copy: "复制服务器邀请",
      copied: "邀请信息已复制",
    },
    outro: {
      title: "专注游戏，管理从简",
      body: "GamePanel Lite 为您提供清晰、便捷、可靠的服务器管理体验。",
    },
    nav: "统一管理 · 4 款游戏",
  },
  en: {
    intro: {
      title: "Professional game server management, made simple",
      body: "Manage games, mods, worlds, and connection details through one clear interface.",
      kicker: "Lightweight · Clear · Reliable",
    },
    library: {
      eyebrow: "Multi-game support",
      title: "Multiple games. One unified experience.",
      body: "Create, configure, start, and stop Terraria, Don't Starve Together, Palworld, and Minecraft servers in one panel.",
      create: "Create server",
      ready: "Configuration complete",
    },
    mods: {
      eyebrow: "Mod management",
      title: "Clear and efficient mod management",
      body: "Search, install, and enable mods from one place, with names, sizes, and requirements clearly presented.",
      heading: "Install mods",
      hint: "Choose from your mod library. Changes apply after a server restart.",
      library: "Mod library 20",
      packs: "Mod packs 1",
      installed: "Installed",
      install: "Install",
      serverOnly: "Server only",
      both: "Server + client",
    },
    backups: {
      eyebrow: "Worlds & backups",
      title: "Reliable protection for every world",
      body: "Save instantly, automate backups, and restore previous versions with confidence.",
      save: "Save world now",
      backup: "Create backup",
      restore: "Restore this version",
      now: "Just now",
      yesterday: "Yesterday, 11:30 PM",
      beforeUpdate: "Before mod update",
      auto: "Automatic backup",
      manual: "Manual backup",
    },
    invite: {
      eyebrow: "Multiplayer access",
      title: "Simple sharing. Seamless connection.",
      body: "Server addresses, ports, and passwords are organized into clear invitation details for accurate sharing.",
      heading: "Game server invitation",
      online: "Server online",
      address: "Server address",
      password: "Room password",
      copy: "Copy server invitation",
      copied: "Invitation details copied",
    },
    outro: {
      title: "Focus on the game. Keep management simple.",
      body: "GamePanel Lite delivers a clear, convenient, and reliable server management experience.",
    },
    nav: "Unified management · 4 games",
  },
} as const;
