services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      network: host
    image: ${GAMEPANEL_IMAGE_REGISTRY:-smartcat99999}/game-panel-lite-api:${GAMEPANEL_IMAGE_TAG:-latest}
    environment:
      GAMEPANEL_HOST: 0.0.0.0
      GAMEPANEL_PORT: 4000
      GAMEPANEL_DATA_DIR: ${GAMEPANEL_WORKSPACE_PATH:-${PWD}}/data
      GAMEPANEL_DB_PATH: ${GAMEPANEL_WORKSPACE_PATH:-${PWD}}/data/gamepanel.db
      GAMEPANEL_DOCKER_HOST: unix:///var/run/docker.sock
    ports:
      - "4000:4000"
    stop_grace_period: 5s
    volumes:
      - ${GAMEPANEL_WORKSPACE_PATH:-${PWD}}:${GAMEPANEL_WORKSPACE_PATH:-${PWD}}
      - ${GAMEPANEL_DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      network: host
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://localhost:4000}
    image: ${GAMEPANEL_IMAGE_REGISTRY:-smartcat99999}/game-panel-lite-web:${GAMEPANEL_IMAGE_TAG:-latest}
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://localhost:4000}
    depends_on:
      - api
    ports:
      - "3001:3000"
