ARG PALWORLD_RUNTIME_VERSION=v2.5.0
FROM thijsvanloef/palworld-server-docker:${PALWORLD_RUNTIME_VERSION}

LABEL org.opencontainers.image.title="GamePanel Lite Palworld Server" \
      org.opencontainers.image.description="Palworld dedicated server runtime for GamePanel Lite" \
      org.opencontainers.image.source="https://github.com/smartcat999/game-panel-lite"
